### ISSUE TITLE
Support VCFs that use `chr_` annotations

### ISSUE THREAD

**Issue by haoyuanli** [CSCfi/beacon-python#171]
#### Describe the bug
Assembled chromosomes for hg38 are chromosomes 1–22 (chr1–chr22), X (chrX), Y (chrY) and Mitochondrial (chrM).

We should consider accepting these in the schema

#### Additional context

Our current schema only supports 1-22, X,  Y and MT

![image](https://user-images.githubusercontent.com/18109953/119535431-d5f19980-bd3c-11eb-8f8c-9a1c92c28073.png)

**Comment by blankdots** [comment]
@haoyuanli it seems that the bug you have described is actually something that is specified in GA4GH beacon specification that this API follows https://github.com/ga4gh-beacon/specification 
If you think that is something that would be beneficial i think it would be better to submit an issue there, and if approved we will include it.

Or as the new 2.0.0 is being developed maybe it would be more appropriate to address under that specification: https://github.com/ga4gh-beacon/specification-v2 which has similar design.

We can adjust the schema in the code base, however we would like to follow the specification as closely as possible. The reasoning for this is that there are other applications and (GA4GH) services that depend on having a consistent specification.

If changing the specification proves too problematic (at the links above), I think there are 2 options with your data format:
- adjust the db to follow the standard formatting of the GA4GH beacon specification
- adjust the code so that we can convert from the format you specify to the standard.

At the same any other suggestions on how this can be addressed is welcomed.

**Comment by haoyuanli** [comment]
Oh totally, thanks for the quick response

I will certainly reach out to the ga4gh beacon to let them know about it. In your experience, are you seeing a lot VCFs that use chr1 instead of 1, let's say?

Best

**Comment by blankdots** [comment]
> I will certainly reach out to the ga4gh beacon to let them know about it. In your experience, are you seeing a lot VCFs that use chr1 instead of 1, let's say?

we haven't tackled much data, and our experience is so far with numbers only: e.g `1`

**Comment by blankdots** [comment]
closing the issue as this seems to be a specification related problem.
